/* =========================================================
   «Η Έξυπνη Σίτα» – sound v2 (from Episode 4 on)
   Recorded sound effects (window.SFXCLIPS, generated by tools/gen_sfx.py and embedded by build.py) and music cues
   (window.MUSICCUES, cut by tools/music_cue.py), played the same way live and in the MP4 export (exportAudio
   decodes them into its offline context before it schedules the events).
     SND2.sfx(name, vol = 1, { rate, pan })        fire-and-forget, at audioNow()
     SND2.music(name, { vol, duck, eq, toFull, lines, fadeOut })
        vol:    gain when featured (linear, default 1; the cue file is already loudness-normalised)
        duck:   gain under the voices (default .4, about -8 dB)
        lines:  [[a, b], …] seconds from the cue's start when somebody speaks (the music dips there)
        eq:     'speaker' (thin, as if from a phone or a Bluetooth speaker in the room) or 'full'
        toFull: seconds after the start when a 'speaker' cue opens to full range (the dramatic moment)
        eqAt:   [[t, 'full' | 'speaker'], …] several colour changes (e.g. full under a logo, then the speaker in the room)
        fadeOut: [start, length] seconds from the cue's start
   Load after engine.js.
   ========================================================= */
const SND2 = (() => {
  const BUF = {}; let decodedFor = null, pending = null;
  function decodeAll(ac) {
    if (decodedFor === ac) return pending;
    decodedFor = ac;
    const all = { ...(window.SFXCLIPS || {}), ...(window.MUSICCUES || {}) };
    pending = Promise.all(Object.entries(all).map(([k, src]) => {
      const bin = atob(src.slice(src.indexOf(',') + 1)), bytes = new Uint8Array(bin.length);
      for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
      return ac.decodeAudioData(bytes.buffer).then(b => { BUF[k] = b; }, e => console.warn('sound decode failed', k, e));
    }));
    return pending;
  }
  function sfx(name, vol = 1, o = {}) {
    if (!AC || !soundOn || !BUF[name]) return;
    const s = AC.createBufferSource(); s.buffer = BUF[name]; if (o.rate) s.playbackRate.value = o.rate;
    const g = AC.createGain(); g.gain.value = vol; s.connect(g);
    if (o.pan && AC.createStereoPanner) { const p = AC.createStereoPanner(); p.pan.value = o.pan; g.connect(p); p.connect(master); } else g.connect(master);
    s.start(audioNow());
  }
  function music(name, o = {}) {
    if (!AC || !soundOn || !BUF[name]) return;
    const n = audioNow(), b = BUF[name], vol = o.vol ?? 1, duck = (o.duck ?? .4) * vol;
    const s = AC.createBufferSource(); s.buffer = b;
    const out = AC.createGain(); out.connect(master);
    // the two colours of the same signal: dry (full range) and "speaker" (band-limited, a little boxy)
    const dry = AC.createGain(), wet = AC.createGain();
    const hp = AC.createBiquadFilter(); hp.type = 'highpass'; hp.frequency.value = 480;
    const lp = AC.createBiquadFilter(); lp.type = 'lowpass'; lp.frequency.value = 3200;
    const pk = AC.createBiquadFilter(); pk.type = 'peaking'; pk.frequency.value = 1500; pk.gain.value = 4; pk.Q.value = .9;
    s.connect(dry); s.connect(hp); hp.connect(lp); lp.connect(pk); pk.connect(wet);
    dry.connect(out); wet.connect(out);
    const speaker = o.eq === 'speaker';
    dry.gain.setValueAtTime(speaker ? 0 : 1, n); wet.gain.setValueAtTime(speaker ? 1.25 : 0, n);
    if (o.eqAt) {   // colour changes over time: [[t, 'full' | 'speaker'], …], a 0.25 s cross-ramp each
      let cur = speaker ? [0, 1.25] : [1, 0];
      for (const [at, c] of o.eqAt.slice().sort((p, q) => p[0] - q[0])) {
        const d = c === 'speaker' ? [0, 1.25] : [1, 0];
        dry.gain.setValueAtTime(cur[0], n + at); wet.gain.setValueAtTime(cur[1], n + at);
        dry.gain.linearRampToValueAtTime(d[0], n + at + .25); wet.gain.linearRampToValueAtTime(d[1], n + at + .25);
        cur = d;
      }
    }
    if (speaker && o.toFull != null) {
      dry.gain.setValueAtTime(0, n + o.toFull); dry.gain.linearRampToValueAtTime(1, n + o.toFull + .25);
      wet.gain.setValueAtTime(1.25, n + o.toFull); wet.gain.linearRampToValueAtTime(0, n + o.toFull + .25);
    }
    // the level: featured, dipping under each line
    out.gain.setValueAtTime(vol, n);
    // lines closer than 0.7 s are one dip (separate dips would overlap and the release of one would cancel the next)
    const dips = [];
    for (const [a, z] of (o.lines || []).slice().sort((p, q) => p[0] - q[0])) { const last = dips[dips.length - 1]; if (last && a - last[1] < .7) last[1] = Math.max(last[1], z); else dips.push([a, z]); }
    for (const [a, z] of dips) {
      out.gain.setValueAtTime(vol, n + Math.max(0, a - .25)); out.gain.linearRampToValueAtTime(duck, n + Math.max(0, a - .05));
      out.gain.setValueAtTime(duck, n + z + .1); out.gain.linearRampToValueAtTime(vol, n + z + .45);
    }
    if (o.fadeOut) { const [a, L] = o.fadeOut; out.gain.setTargetAtTime(0, n + a, L / 3); }
    s.start(n);
  }
  return { decodeAll, sfx, music, BUF };
})();
