/* Ep.3, Scene 19 – «Η αποκάλυψη»: evening in the yard. Κώστας, two beers in (tipsy, not Panik), shows Γιάννος his «spam» as a joke.
   Γιάννος reads «…με δωρεάν μεταφορικά», finds his agent's signature in the metadata, and freezes. «Καλά. Άμα πάρει τηλέφωνο, πες ότι λείπω.» */
defineScene((() => {
const X = { giannos: 460, kostas: 640, mimis: 820, christos: 1000 };
const CAMS = { wide: [700, 420, 1.1], kos: [640, 380, 2.1], gia: [460, 380, 2.1], two: [550, 400, 1.6], phone: [0, 0, 1], giaC: [460, 370, 2.8], mim: [820, 400, 2.1], chr: [1000, 400, 2.1] };
const steps = [
  { act: 'eve', d: 2.4, cam: 'wide' },
  { who: 'kostas', cam: 'kos', mark: 'spam', el: 'Κοίτα. Μου στέλνει spam μια εταιρεία ρεύματος. Εδώ και μήνες.', en: "Look. Some power company's been spamming me. For months now." },
  { who: 'kostas', cam: 'two', el: 'Ούτε unsubscribe δεν έχει.', en: "It doesn't even have an unsubscribe." },
  { who: 'giannos', cam: 'phone', mark: 'read', el: '«Παράσιτο. Η έξυπνη επανάσταση έρχεται».', en: '"Parasite. The smart revolution is coming".' },
  { who: 'giannos', cam: 'gia', mark: 'what', el: '…Κώστα. Τι της απαντάς;', en: '…Kostas. What do you answer her?' },
  { who: 'kostas', cam: 'kos', el: 'Ό,τι μου έρθει. Μαρμοκοτρόκο, σικαρέλο… Διάλεξε.', en: 'Whatever comes to mind. Marmokotroko, sikarelo… Take your pick.' },
  { act: 'meta', d: 2.2, cam: 'phone' },
  { who: 'giannos', cam: 'giaC', mark: 'sig', el: 'Αυτή είναι η υπογραφή του δικού μου agent.', en: "That's my own agent's signature." },
  { who: 'giannos', cam: 'giaC', mark: 'alive', el: 'Ζει. Και σου γράφει εδώ και μήνες.', en: "She's alive. And she's been texting you for months." },
  { who: 'kostas', cam: 'kos', mark: 'away', el: 'Καλά. Άμα πάρει τηλέφωνο, πες ότι λείπω.', en: "Fine. If she calls, tell her I'm out." },
  { act: 'stand', d: 1.4, cam: 'wide' },
  { who: 'giannos', cam: 'gia', mark: 'warn', el: 'Να δείτε. Δεν έχουμε τελειώσει με τη σίτα.', en: "Mark my words. We're not done with the σίτα." },
  { who: 'mimis', cam: 'mim', el: 'Εντάξει.', en: 'Okay.' },
  { who: 'christos', cam: 'chr', mark: 'drew', el: 'Το ξέρω. Το ζωγράφισα.', en: 'I know. I drew it.' },
  { act: 'end', d: 1.6, cam: 'wide' },
];
let M;
function render(t, _M, sc) {
  M = _M;
  const [, shot] = shotAt(sc, t);
  if (shot === 'phone') {
    const meta = t > M.meta.a;
    smsScreen(t, [{ me: false, text: 'ΣΕ ΠΑΡΑΚΟΛΟΥΘΩ.', at: -1 }, { me: true, text: 'Κούκι τρας.', at: -1 }, { me: false, text: 'ΠΑΡΑΣΙΤΟ. Η ΕΞΥΠΝΗ ΕΠΑΝΑΣΤΑΣΗ ΕΡΧΕΤΑΙ.', at: -1 }, { me: true, text: 'Μπαμπαλίκι σκρατς.', at: -1 }], { red: true });
    if (meta) { ctx.save(); ctx.setTransform(1, 0, 0, 1, 0, 0); const k = ease(prog(t, M.meta.a, M.meta.a + .5));
      rect(420, 470 - k * 120, 440, 150, '#1e2533', { lw: 3, sc: '#7ad8ff' }); txt('Λεπτομέρειες μηνύματος', 640, 500 - k * 120, 18, '#9aa7bd', { font: 'monospace', weight: 700 });
      txt('X-Mailer: generated by agent-v1', 640, 545 - k * 120, 22, '#ffd23f', { font: 'monospace', weight: 900 }); txt('(c) Γιάννος', 640, 580 - k * 120, 18, '#9aa7bd', { font: 'monospace', weight: 700 }); ctx.restore(); }
    return;
  }
  const c = shotCam(sc, t, CAMS);
  ctx.save(); applyCam(c);
  yard(t, { light: 'dusk', doorLit: true });
  const la = (who, rest) => lookAtSpeaker(t, who, X, rest);
  const shown = t > M.spam.a + .4 && t < M.away.a, frozen = t > M.sig.a;
  tableOf(t, [
    [X.giannos, 'giannos', { t, talk: talk('giannos', t), look: shown ? [.3, .6] : la('giannos', [1, 0]), brow: frozen ? 'worry' : 'flat', mouth: frozen ? 'frown' : 'flat', R: shown ? [60, -130] : gesture(t, talk('giannos', t)), itemR: shown ? 'phone' : null }],
    [X.kostas, 'kostas', { t, talk: talk('kostas', t), look: la('kostas', [-1, 0]), lid: true, mouth: 'smirk', tilt: Math.sin(t * .9) * .05, L: [-40, -100], itemL: 'beer', R: inM(t, M.spam) ? [-60, -120] : [44, -40] }],
    [X.mimis, 'mimis', { t, talk: talk('mimis', t), look: la('mimis', [-1, 0]), lid: true, mouth: 'flat', R: [50, -100], itemR: 'cup2' }],
    [X.christos, 'christos', { t, talk: talk('christos', t), look: la('christos', [-1, .2]), mouth: 'flat', L: [-30, -110], R: [30 + Math.sin(t * 12) * 8, -100], itemL: 'sketch' }],
  ], {});
  for (const x of [600, 630]) beerCan(x, 540, .9);
  ctx.restore();
  applyLight('dusk', .8);
  if (inM(t, M.alive, .3, 0)) sfxText('ΖΕΙ.', 460, 150, 60, -.06, '#ff4040');
  vignette(.4);
}
return {
  id: 'scene19', title: '19 · Η αποκάλυψη', steps, render,
  events: M => [[M.eve.a + .3, () => noise(.3, .1, 3000, 1, 'bandpass')], [M.meta.a + .3, SFX.pop], [M.sig.a - .2, () => tone(260, 1.5, 'sine', .05, .7)], [M.alive.b, SFX.jingleMinor]],
  ambience: () => ({ cicada: .01, cricket: .02 }),
};
})());
